### ISSUE TITLE
Dale a ver qué te parece...

### ISSUE THREAD

**Issue by fernand0** [ReVision-Docencia-20/Columnas#1]
... primeras ideas, a ver si te encaja y por dónde podemos seguir.... @JJ

**Comment by fernand0** [comment]
He cambiado lo de las otras titulaciones y me he acordado del marco de competencias digitales de la CE. Si te parece @JJ lo dejamos madurando para re-leerlo mañana y lo mandamos.

**Comment by JJ** [comment]
Mañana tengo casi 24 horas de viaje por delante. No creo que me dé tiempo.
Le doy un repaso ahora y con lo que tú digas envíalo.

**Comment by JuanjoUE** [comment]
Saludos, estoy perdido...
Me ha llegado este correo y “ninguno más ni antes ni después”
Y, la verdad, no eh sabido cómo proceder.
¿Hay alguien ahí que me oriente un poco para recuperar el hilo publicador con vosotros dos?

----
Juan José Escribano Otero
91 2115672 – www.universidadeuropea.es<http://www.universidadeuropea.es/>
https://www.youtube.com/watch?v=PDYJOyWWyS4

De: Fernando Tricas García [mailto:notifications@github.com]
Enviado el: domingo, 07 de mayo de 2017 20:18
Para: ReVision-Docencia-20/Columnas <Columnas@noreply.github.com>
CC: Subscribed <subscribed@noreply.github.com>
Asunto: Re: [ReVision-Docencia-20/Columnas] Dale a ver qué te parece... (#1)


He cambiado lo de las otras titulaciones y me he acordado del marco de competencias digitales de la CE. Si te parece @JJ<https://github.com/JJ> lo dejamos madurando para re-leerlo mañana y lo mandamos.

**Comment by JJ** [comment]
Ahora vamos a columna cada seis meses. Usamos el directorio "En cocina"
para las nuevas columnas, ideas o lo que sea. Y cuando se escriba algo, con
@ nombre avisamos de lo que hemos hecho. Anímate :-=
